[settings]
description = "Text editor configuration cluster"
url = "git@github.com:awkles/editor-cluster.git"
work_tree_alias = "$HOME"

[[dependencies]]
name = "shell"
url = "git@github.com:awkless/shell-cluster.git"
